USE [master]
GO
CREATE DATABASE [oledb-test]
ALTER DATABASE [oledb-test] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [oledb-test].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [oledb-test] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [oledb-test] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [oledb-test] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [oledb-test] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [oledb-test] SET ARITHABORT OFF 
GO
ALTER DATABASE [oledb-test] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [oledb-test] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [oledb-test] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [oledb-test] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [oledb-test] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [oledb-test] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [oledb-test] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [oledb-test] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [oledb-test] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [oledb-test] SET  DISABLE_BROKER 
GO
ALTER DATABASE [oledb-test] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [oledb-test] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [oledb-test] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [oledb-test] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [oledb-test] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [oledb-test] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [oledb-test] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [oledb-test] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [oledb-test] SET  MULTI_USER 
GO
ALTER DATABASE [oledb-test] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [oledb-test] SET DB_CHAINING OFF 
GO
ALTER DATABASE [oledb-test] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [oledb-test] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [oledb-test] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [oledb-test] SET QUERY_STORE = OFF
GO
USE [oledb-test]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NOT NULL,
	[Age] [int] NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustomerAddress](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerId] [int] NOT NULL,
	[House] [varchar](255) NOT NULL,
	[Street] [varchar](255) NOT NULL,
	[County] [varchar](255) NOT NULL,
	[Country] [varchar](255) NULL,
 CONSTRAINT [PK_CustomerAddress] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Customer] ON 
GO
INSERT [dbo].[Customer] ([Id], [Name], [Age]) VALUES (1, N'Test User', 99)
GO
SET IDENTITY_INSERT [dbo].[Customer] OFF
GO
SET IDENTITY_INSERT [dbo].[CustomerAddress] ON 
GO
INSERT [dbo].[CustomerAddress] ([Id], [CustomerId], [House], [Street], [County], [Country]) VALUES (1, 1, N'1', N'Test Street', N'Test County', N'Test Country')
GO
SET IDENTITY_INSERT [dbo].[CustomerAddress] OFF
GO
ALTER TABLE [dbo].[CustomerAddress]  WITH CHECK ADD  CONSTRAINT [FK_Customer_CustomerAddress] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[CustomerAddress] CHECK CONSTRAINT [FK_Customer_CustomerAddress]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[InsertCustomer]
	@Name varchar(255),
	@Age int,
	@House varchar(255),
	@Street varchar(255),
	@County varchar(255),
	@Country varchar(255) null
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO dbo.Customer
	(Name, Age)
	VALUES
	(@Name, @Age);

	INSERT INTO dbo.CustomerAddress
	(CustomerId, House, Street, County, Country)
	VALUES
	(SCOPE_IDENTITY(), @House, @Street, @County, @Country);
END
GO
USE [master]
GO
ALTER DATABASE [oledb-test] SET  READ_WRITE 
GO
